name: Update feed.xml

on:
  schedule:
    - cron: '0 0 * * *' # 매일 자정에 실행
  push:
    branches:
      - main

jobs:
  update-feed:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Fetch feed.xml from GitHub Pages
        run: curl -o feed.xml https://goldneck.github.io/feed.xml

      - name: Commit and push changes
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add feed.xml
          git commit -m 'Update feed.xml'
          git push
